### ISSUE TITLE
no IP and exited

### ISSUE THREAD

**Issue by Narcolapser** [myrjola/docker-samba-ad-dc#4]
I've got a clean install of Ubuntu, apt-get update; apt-get upgrade has been run, and git installed to clone this repo, but other wise clean 14.04. I clone this repo and run the commands as listed. But when I get to searching for the IP Address i get:
     "IPAddress"":""

I run "docker ps", I get nothing. I run "docker ps -a" and it says Exit(127). Any idea what's wrong here?

**Comment by myrjola** [comment]
Hi Narcolapser!

I can reproduce this as well. Seems that a newer samba-version doesn't include the samba-tool binary, or then Ubuntu's samba packaging has changed.

```
➜  docker-samba-ad-dc git:(master) docker ps -a
CONTAINER ID        IMAGE                COMMAND                CREATED             STATUS                       PORTS               NAMES
bda3cac9ea4b        samba-ad-dc:latest   "/init.sh app:start"   2 hours ago         Exited (127) 2 minutes ago                       dc1
➜  docker-samba-ad-dc git:(master) docker logs bda3cac9ea4b
Root password: aejau3gee2Ie
Samba administrator password: OoY3shei.c
Kerberos KDC database master key: deu5aa'Cie
/init.sh: line 27: samba-tool: command not found
```

I'm not maintaining this repository anymore. But feel free to fork it.
