### ISSUE TITLE
i am not sure is this docker issue or what

### ISSUE THREAD

**Issue by addhe** [myrjola/docker-samba-ad-dc#5]
Sending build context to Docker daemon 82.94 kB
Sending build context to Docker daemon
Step 0 : FROM ubuntu:12.04.5
 ---> 69c02692b0c1
Step 1 : MAINTAINER Martin Yrjölä <martin.yrjola@gmail.com>
 ---> Using cache
 ---> 99d7ccb57b2b
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 2c4bbeb194f8
Step 3 : RUN apt-get update
INFO[0000] Unknown filesystem type on /dev/mapper/docker-253:0-524719-4cce267aed7dfeafe4b4d3f4fc7ef9f1d5327a90af98239a3c97ead80a74f168-init

**Comment by myrjola** [comment]
Yeah, seems to be an issue with your Docker setup.
